level: debug

worker:
  temp_dir: /tempfs
  threads_per_worker: ${worker_threads}
  jobs: ${worker_jobs}

health:
  enabled: true
  bind: "0.0.0.0:9000"

monitoring:
  enabled: true
  bind: "0.0.0.0:9100"

message_queue:
  mode: "RMQ"
  jobs_queue: "seventv_image_processor_jobs"
  rmq:
    uri: ${rmq_uri}
    max_reconnect_attempts: 10

s3:
  region: ${s3_region}
  access_token: "${s3_access_key}"
  secret_key: "${s3_secret_key}"
  endpoint: "${s3_endpoint}"