level: debug

worker:
  temp_dir: /tempfs
  threads_per_worker: ${worker_threads}
  jobs: ${worker_jobs}

health:
  enabled: true
  bind: "0.0.0.0:9000"

monitoring:
  enabled: true
  bind: "0.0.0.0:9100"

message_queue:
  rmq:
    uri: ${rmq_uri}
    max_reconnect_attempts: 10
