version: 2.1
workflows:
  lint:
    jobs:
      - lint

orbs:
  node: circleci/node@5.0.2
  go: circleci/go@1.7.1
  python: circleci/python@2.0.3

jobs:
  lint:
    resource_class: seventv/self-hosted
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          name: Install Deps
          command: |
            sudo apt-get update
            sudo apt-get install make build-essential python3 python3-pip -y
      - node/install:
          install-yarn: true
          node-version: "18"
      - go/install:
          version: "1.18.1"
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export PATH=$(go env GOPATH)/bin:$HOME/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install dev_deps
          command: make dev_deps
      - run:
          name: Linter
          command: make lint
