version: 2.1
workflows:
  lint:
    jobs:
      - lint
  build:
    jobs:
      - build

orbs:
  node: circleci/node@5.0.2
  go: circleci/go@1.7.1
  python: circleci/python@2.0.3

jobs:
  lint:
    resource_class: seventv/self-hosted
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          name: Install Deps
          command: |
            echo 'export NVM_DIR="$HOME/.nvm"' >> "$BASH_ENV";
            sudo apt-get update
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
              make \
              build-essential \
              python3 \
              python3-pip \
              git
      - node/install:
          install-yarn: true
          node-version: "18"
      - go/install:
          version: "1.18.1"
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export PATH=$(go env GOPATH)/bin:$HOME/.local/bin:$PATH' >> $BASH_ENV
      - restore_cache:
          keys:
            - python-cache-{{ arch }}-{{ checksum "cpp/requirements.txt"  }}
            - python-cache-{{ arch }}
      - restore_cache:
          keys:
            - go-mod-cache-{{ arch }}-{{ checksum "go/go.sum"  }}
            - go-mod-cache-{{ arch }}
      - restore_cache:
          keys:
            - go-build-cache-{{ arch }}-{{ checksum "go/go.sum"  }}
            - go-build-cache-{{ arch }}
      - run:
          name: Install dev_deps
          command: make dev_deps
      - run:
          name: Linter
          command: make lint
      - save_cache:
          key: python-cache-{{ arch }}-{{ checksum "cpp/requirements.txt"  }}
          paths:
            - /home/circle/.cache/pip
      - save_cache:
          key: go-mod-cache-{{ arch }}-{{ checksum "go/go.sum"  }}
          paths:
            - /home/circleci/go/pkg/mod
      - save_cache:
          key: go-build-cache-{{ arch }}-{{ checksum "go/go.sum"  }}
          paths:
            - /home/circle/.cache/go-build
  build:
    resource_class: seventv/self-hosted
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
            - v1
      - run:
          name: Install docker
          command: |
            sudo apt-get update 
            sudo apt-get install docker.io
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            DOCKER_BUILDKIT=1 docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
