version: 2.1
workflows:
  lint:
    jobs:
      - lint_go

jobs:
  lint:
    machine: true
    resource_class: seventv/self-hosted
    steps:
      - checkout
      - name: Install make
        run: apt-get update && apt-get install make
