version: 2.1
workflows:
  lint:
    jobs:
      - lint
  build:
    jobs:
      - deps-builder:
          pre-steps:
            - runner/setup
          post-steps:
            - runner/cleanup

orbs:
  node: circleci/node@5.0.2
  go: circleci/go@1.7.1
  python: circleci/python@2.0.3
  runner:
    commands:
      setup:
        steps:
          - run:
              when: always
              name: Setup the runner
              command: |
                ln -s . /opt/circleci/workdir/current
                mkdir -p ~/.ssh 
                ssh-keyscan github.com >> ~/.ssh/known_hosts
                docker context create builder
                docker buildx create --name=builder --use builder
      cleanup:
        steps:
          - run:
              when: always
              name: Cleanup the runner
              command: |
                rm /opt/circleci/workdir/current
                rm ~/.ssh/known_hosts
                docker buildx rm builder
                docker context rm builder
                docker ps -q | grep . && docker kill $(docker ps -q) || true
                docker system prune --force --all

jobs:
  lint:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install Deps
          command: |
            echo 'export NVM_DIR="$HOME/.nvm"' >> "$BASH_ENV";
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
              make \
              build-essential \
              python3 \
              python3-pip \
              git \
              curl
      - node/install:
          install-yarn: true
          node-version: "18"
      - go/install:
          version: "1.18.1"
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export PATH=$(go env GOPATH)/bin:$HOME/.local/bin:$PATH' >> $BASH_ENV
      - restore_cache:
          keys:
            - python-cache-{{ arch }}-{{ checksum "cpp/requirements.txt"  }}
            - python-cache-{{ arch }}
      - restore_cache:
          keys:
            - go-mod-cache-{{ arch }}-{{ checksum "go/go.sum" }}
            - go-mod-cache-{{ arch }}
      - restore_cache:
          keys:
            - go-build-cache-{{ arch }}-{{ checksum "go/go.sum"  }}
            - go-build-cache-{{ arch }}
      - run:
          name: Install dev_deps
          command: make dev_deps
      - run:
          name: Linter
          command: make lint
      - save_cache:
          key: python-cache-{{ arch }}-{{ checksum "cpp/requirements.txt"  }}
          paths:
            - /home/circle/.cache/pip
      - save_cache:
          key: go-mod-cache-{{ arch }}-{{ checksum "go/go.sum"  }}
          paths:
            - /home/circleci/go/pkg/mod
      - save_cache:
          key: go-build-cache-{{ arch }}-{{ checksum "go/go.sum"  }}
          paths:
            - /home/circle/.cache/go-build
  deps-builder:
    resource_class: seventv/self-hosted
    machine:
      image: ubuntu:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - third-party-{{ .Branch }}
            - third-party
      - run:
          name: Fetch Submodules
          command: |
            git submodule update --init --recursive
      - save_cache:
          key: third-party-{{ .Branch }}-{{ epoch }}
          paths:
            - /opt/circleci/workdir/current/cpp/third-party
      - restore_cache:
          keys:
            - deps-builder-{{ .Branch }}
            - deps-builder
      - run:
          name: Build application Docker image
          command: |
            docker buildx build \
              --target deps-builder \
              --cache-from=type=local,src=/opt/circleci/workdir/current/.cache/deps-builder \
              --cache-to=type=local,dest=/opt/circleci/workdir/current/.cache/deps-builder \
              --progress plain \
              .
      - save_cache:
          key: deps-builder-{{ .Branch }}-{{ epoch }}
          paths:
            - /opt/circleci/workdir/current/.cache/deps-builder
