version: 2.1
workflows:
  lint:
    jobs:
      - lint

orbs:
  node: circleci/node@5.0.2
  go: circleci/go@1.7.1
  python: circleci/python@2.0.3

jobs:
  lint:
    resource_class: seventv/self-hosted
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          name: Install Deps
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              make \
              build-essential \
              python3 \
              python3-pip \
              git
            sudo ln -s $(which pip3) /usr/local/bin/pip
            sudo ln -s $(which python3) /usr/local/bin/python
      - node/install:
          install-yarn: true
          node-version: "18"
      - go/install:
          version: "1.18.1"
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export PATH=$(go env GOPATH)/bin:$HOME/.local/bin:$PATH' >> $BASH_ENV
      - restore_cache:
          keys:
            - python-cache-{{ arch }}-{{ checksum "cpp/requirements.txt"  }}
            - python-cache-{{ arch }}
      - restore_cache:
          keys:
            - go-mod-cache-{{ arch }}-{{ checksum "go/go.sum"  }}
            - go-mod-cache-{{ arch }}
      - restore_cache:
          keys:
            - go-build-cache-{{ arch }}-{{ checksum "go/go.sum"  }}
            - go-build-cache-{{ arch }}
      - run:
          name: Install dev_deps
          command: make dev_deps
      - run:
          name: Linter
          command: make lint
      - save_cache:
          key: python-cache-{{ arch }}-{{ checksum "cpp/requirements.txt"  }}
          paths:
            - "{{ pip3 cache dir }}"
      - save_cache:
          key: go-mod-cache-{{ arch }}-{{ checksum "go/go.sum"  }}
          paths:
            - "{{ go env GOMODCACHE }}"
      - save_cache:
          key: go-build-cache-{{ arch }}-{{ checksum "go/go.sum"  }}
          paths:
            - "{{ go env GOCACHE }}"
