version: 2.1
workflows:
  lint:
    jobs:
      - lint

jobs:
  lint:
    resource_class: seventv/self-hosted
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          name: Install make
          command: |
            sudo apt-get update
            sudo apt-get install make
