version: 2.1
workflows:
  lint:
    jobs:
      - lint

jobs:
  lint:
    machine: true
    resource_class: seventv/self-hosted
    steps:
      - checkout
      - run:
          name: Install make
          command: |
            apt-get update
            apt-get install make
