version: 2.1
workflows:
  lint:
    jobs:
      - lint

orbs:
  node: circleci/node@5.0.2
  go: circleci/go@1.7.1

jobs:
  lint:
    resource_class: seventv/self-hosted
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          name: Install make
          command: |
            apt-get update
            apt-get install make build-essential
      - node/install:
          install-yarn: true 
          node-version: '18'
      - go/install:
          version: '1.18.1' 
