on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - uses: actions/setup-python@v3
        with:
          python-version: "3.8.10"

      - name: Checkout code
        uses: actions/checkout@v3

      - id: cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
          echo "::set-output name=python-pip::$(python3 -m pip cache dir)"

      - name: Go Build Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('go/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('go/go.sum') }}

      - name: Python Pip Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache-paths.outputs.python-pip }}
          key: ${{ runner.os }}-python-pip-${{ hashFiles('cpp/requirements.txt') }}

      - name: Node Modules Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

      - name: install dev_deps
        run: make dev_deps

      - name: Run Lint
        run: make lint
  deps-builder:
    name: Deps Builder
    runs-on: self-hosted
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - id: buildx-context
        run: |
          docker context create builders

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
          endpoint: builders

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache/deps-builder
          key: ${{ runner.os }}-deps-builder-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-deps-builder-buildx-

      - name: Build the cache
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache/deps-builder
          cache-to: type=local,dest=/tmp/.buildx-cache/deps-builder-new,mode=max
          target: deps-builder

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache/deps-builder
          mv /tmp/.buildx-cache/deps-builder-new /tmp/.buildx-cache/deps-builder
