name: Build Image Processor

on:
  push:
    branches: [troy/init]

  workflow_dispatch:

jobs:
  build:
    name: Build Image Processor
    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Log into Harbor Registry
        uses: docker/login-action@v1
        with:
          registry: harbor.disembark.dev
          username: robot$deploy-7tv
          password: ${{ secrets.REGISTRY_TOKEN }}

      - id: buildx-context
        run: |
          docker context create builders

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
          endpoint: builders

      - name: Build Image
        id: build_step
        uses: docker/build-push-action@v2
        with:
          build-args: |
            "BUILDER=${{ github.actor }}"
            "VERSION=${{ github.sha }}"
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            harbor.disembark.dev/7tv/image-processor-dev:${{ github.sha }}
            harbor.disembark.dev/7tv/image-processor-dev:latest
