on:
  push:
    branches:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.18.1]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.2.0
        with:
          go-version: ${{ matrix.go }}
        id: go

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: lint
        run: make lint
